const lOG_IN_PAGE_ROUTE = '/'; // PUT THESE IN ROUTES_ENUM - done
const MAIN_PAGE_ROUTE = '/spoofy';
const SONG_TABLE_ROUTE = '/songTable';
const PLAYLIST_TABLE_ROUTE = '/playlistTable';
const FAVORITE_TABLE_ROUTE = '/favoriteTable';
const LOCATION_ROUTE = '/location';

export enum RouteMapper {
  LOGIN = lOG_IN_PAGE_ROUTE,
  MAIN_PAGE = MAIN_PAGE_ROUTE,
  SONG = SONG_TABLE_ROUTE,
  PLAYLIST = PLAYLIST_TABLE_ROUTE,
  FAVORITE = FAVORITE_TABLE_ROUTE,
  LOCATION = LOCATION_ROUTE,
}
